language: php

# environment variable used in test suite
env:
  global:
  - TASK_TESTS_COVERAGE=0

dist: precise

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
  - vendor
  - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
  - php: 7.2
  # run tests coverage on PHP 7.1
  - php: 7.1
    env: TASK_TESTS_COVERAGE=1
  - php: 5.6

# install dependencies
install:
- travis_retry composer self-update
- travis_retry composer global require "codeception/codeception"
- travis_retry composer install --prefer-dist
- travis_retry composer require carono/yii2-giix
- travis_retry composer require yiisoft/yii2-gii

before_script:
- mysql -e 'create database test;'
- psql -c 'create database test' -U postgres
- ~/.composer/vendor/bin/codecept build
- php tests/app/yii migrate --interactive=0 --db=db
- php tests/app/yii migrate --interactive=0 --db=db2

script:
- ~/.composer/vendor/bin/codecept run --env pgsql,mysql --coverage-xml

after_script:
- |
  if [ $TASK_TESTS_COVERAGE == 1 ]; then
    travis_retry wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover tests/output/coverage.xml
  fi